# Lab | Data Cleaning and Formatting

In this lab, we will be working with the customer data from an insurance company, which can be found in the CSV file located at the following link: https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv

# Challenge 1: Data Cleaning and Formatting

## Exercise 1: Cleaning Column Names

To ensure consistency and ease of use, standardize the column names of the dataframe. Start by taking a first look at the dataframe and identifying any column names that need to be modified. Use appropriate naming conventions and make sure that column names are descriptive and informative.

*Hint*:
- *Column names should be in lower case*
- *White spaces in column names should be replaced by `_`*
- *`st` could be replaced for `state`*

In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
# Your code here
import pandas as pd

df = pd.read_csv("https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv")

df.columns = (df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ","_")
    )

In [3]:
df

,customer,st,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.59%,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17%,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,764586.18%,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,536307.65%,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323
...,...,...,...,...,...,...,...,...,...,...,...
4003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4008 entries, 0 to 4007
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   customer                   1071 non-null   object
 1   st                         1071 non-null   object
 2   gender                     954 non-null    object
 3   education                  1071 non-null   object
 4   customer_lifetime_value    1068 non-null   object
 5   income                     1071 non-null   float64
 6   monthly_premium_auto       1071 non-null   float64
 7   number_of_open_complaints  1071 non-null   object
 8   policy_type                1071 non-null   object
 9   vehicle_class              1071 non-null   object
 10  total_claim_amount         1071 non-null   float64
dtypes: float64(3), object(8)
memory usage: 344.6+ KB

## Exercise 2: Cleaning invalid Values

The dataset contains columns with inconsistent and incorrect values that could affect the accuracy of our analysis. Therefore, we need to clean these columns to ensure that they only contain valid data.

Note that this exercise will focus only on cleaning inconsistent values and will not involve handling null values (NaN or None).

*Hint*:
- *Gender column contains various inconsistent values such as "F", "M", "Femal", "Male", "female", which need to be standardized, for example, to "M" and "F".*
- *State abbreviations be can replaced with its full name, for example "AZ": "Arizona", "Cali": "California", "WA": "Washington"*
- *In education, "Bachelors" could be replaced by "Bachelor"*
- *In Customer Lifetime Value, delete the `%` character*
- *In vehicle class, "Sports Car", "Luxury SUV" and "Luxury Car" could be replaced by "Luxury"*

In [5]:
df["gender"].value_counts()

gender
F         457
M         413
Male       39
female     28
Femal      17
Name: count, dtype: int64

In [6]:
# Your code here
# clean gender
df["gender"]= df["gender"].str.strip().replace({
    "Male":"M",
    "female":"F",
    "Femal":"F"
    })

df["gender"].value_counts()

gender
F    502
M    452
Name: count, dtype: int64

In [7]:
df["st"]= df["st"].str.strip().replace({
    "AZ":"Arizona",
    "Cali":"California",
    "WA":"Washington"
    })
df.st.value_counts()

st
California    331
Oregon        320
Arizona       211
Washington    111
Nevada         98
Name: count, dtype: int64

In [8]:
df.loc[df["education"]=="Bachelors",["education"]]="Bachelor"
df.education.value_counts()

education
Bachelor                331
College                 313
High School or Below    296
Master                   94
Doctor                   37
Name: count, dtype: int64

In [9]:
df["customer_lifetime_value"]= df["customer_lifetime_value"].str.strip().str.replace("%","")

In [10]:
condition = df["vehicle_class"].isin([
    "Sports Car",
    "Luxury SUV",
    "Luxury Car"
])
df.loc[condition,["vehicle_class"]]="Luxury"

## Exercise 3: Formatting data types

The data types of many columns in the dataset appear to be incorrect. This could impact the accuracy of our analysis. To ensure accurate analysis, we need to correct the data types of these columns. Please update the data types of the columns as appropriate.

It is important to note that this exercise does not involve handling null values (NaN or None).

*Hint*:
- *Customer lifetime value should be numeric*
- *Number of open complaints has an incorrect format. Look at the different values it takes with `unique()` and take the middle value. As an example, 1/5/00 should be 5. Number of open complaints is a string - remember you can use `split()` to deal with it and take the number you need. Finally, since it should be numeric, cast the column to be in its proper type.*

In [11]:
# Your code here
df.customer_lifetime_value=df.customer_lifetime_value.map(float)

In [12]:
df.number_of_open_complaints.unique()

array(['1/0/00', '1/2/00', '1/1/00', '1/3/00', '1/5/00', '1/4/00', nan],
      dtype=object)

In [13]:
df.number_of_open_complaints=df.number_of_open_complaints.map(lambda x : x.split("/")[1] if pd.notna(x) else x).astype("Int64")

In [14]:
df.head(10)

,customer,st,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,0,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.59,0.0,94.0,0,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17,48767.0,108.0,0,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,764586.18,0.0,106.0,0,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,536307.65,36357.0,68.0,0,Personal Auto,Four-Door Car,17.269323
5,OC83172,Oregon,F,Bachelor,825629.78,62902.0,69.0,0,Personal Auto,Two-Door Car,159.383042
6,XZ87318,Oregon,F,College,538089.86,55350.0,67.0,0,Corporate Auto,Four-Door Car,321.600000
7,CF85061,Arizona,M,Master,721610.03,0.0,101.0,0,Corporate Auto,Four-Door Car,363.029680
8,DY87989,Oregon,M,Bachelor,2412750.40,14072.0,71.0,0,Corporate Auto,Four-Door Car,511.200000
9,BQ94931,Oregon,F,College,738817.81,28812.0,93.0,0,Special Auto,Four-Door Car,425.527834

## Exercise 4: Dealing with Null values

Identify any columns with null or missing values. Identify how many null values each column has. You can use the `isnull()` function in pandas to find columns with null values.

Decide on a strategy for handling the null values. There are several options, including:

- Drop the rows or columns with null values
- Fill the null values with a specific value (such as the column mean or median for numerical variables, and mode for categorical variables)
- Fill the null values with the previous or next value in the column
- Fill the null values based on a more complex algorithm or model (note: we haven't covered this yet)

Implement your chosen strategy to handle the null values. You can use the `fillna()` function in pandas to fill null values or `dropna()` function to drop null values.

Verify that your strategy has successfully handled the null values. You can use the `isnull()` function again to check if there are still null values in the dataset.

Remember to document your process and explain your reasoning for choosing a particular strategy for handling null values.

After formatting data types, as a last step, convert all the numeric variables to integers.

In [15]:
# Your code here
df=df.dropna(how="all")
df

,customer,st,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,0,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.59,0.0,94.0,0,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17,48767.0,108.0,0,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,764586.18,0.0,106.0,0,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,536307.65,36357.0,68.0,0,Personal Auto,Four-Door Car,17.269323
...,...,...,...,...,...,...,...,...,...,...,...
1066,TM65736,Oregon,M,Master,305955.03,38644.0,78.0,1,Personal Auto,Four-Door Car,361.455219
1067,VJ51327,California,F,High School or Below,2031499.76,63209.0,102.0,2,Personal Auto,SUV,207.320041
1068,GS98873,Arizona,F,Bachelor,323912.47,16061.0,88.0,0,Personal Auto,Four-Door Car,633.600000
1069,CW49887,California,F,Master,462680.11,79487.0,114.0,0,Special Auto,SUV,547.200000
1070,MY31220,California,F,College,899704.02,54230.0,112.0,0,Personal Auto,Two-Door Car,537.600000

In [16]:
df = df.copy()
df["gender"] = df["gender"].fillna("Unknown")
df["customer_lifetime_value"] = df["customer_lifetime_value"].fillna("Unknown")

In [41]:
df["customer_lifetime_value"]= df["customer_lifetime_value"].map(lambda x: int(x) if x != "Unknown" else x)

In [44]:
df["customer_lifetime_value"].apply(type).value_counts()

customer_lifetime_value
<class 'int'>    1068
<class 'str'>       3
Name: count, dtype: int64

In [18]:
df.isna().sum()

customer                     0
st                           0
gender                       0
education                    0
customer_lifetime_value      0
income                       0
monthly_premium_auto         0
number_of_open_complaints    0
policy_type                  0
vehicle_class                0
total_claim_amount           0
dtype: int64

In [19]:
df.dtypes

customer                      object
st                            object
gender                        object
education                     object
customer_lifetime_value       object
income                       float64
monthly_premium_auto         float64
number_of_open_complaints      Int64
policy_type                   object
vehicle_class                 object
total_claim_amount           float64
dtype: object

In [20]:
df[["income","monthly_premium_auto","total_claim_amount"]]=df[["income","monthly_premium_auto","total_claim_amount"]].astype(int)

In [21]:
df.dtypes

customer                     object
st                           object
gender                       object
education                    object
customer_lifetime_value      object
income                        int64
monthly_premium_auto          int64
number_of_open_complaints     Int64
policy_type                  object
vehicle_class                object
total_claim_amount            int64
dtype: object

## Exercise 5: Dealing with duplicates

Use the `.duplicated()` method to identify any duplicate rows in the dataframe.

Decide on a strategy for handling the duplicates. Options include:
- Dropping all duplicate rows
- Keeping only the first occurrence of each duplicated row
- Keeping only the last occurrence of each duplicated row
- Dropping duplicates based on a subset of columns
- Dropping duplicates based on a specific column

Implement your chosen strategy using the `drop_duplicates()` function.

Verify that your strategy has successfully handled the duplicates by checking for duplicates again using `.duplicated()`.

Remember to document your process and explain your reasoning for choosing a particular strategy for handling duplicates.

Save the cleaned dataset to a new CSV file.

*Hint*: *after dropping duplicates, reset the index to ensure consistency*.

In [22]:
# Your code here
df.duplicated().value_counts()
df.to_csv('cleaned_dataset.csv', index=False)

# Bonus: Challenge 2: creating functions on a separate `py` file

Put all the data cleaning and formatting steps into functions, and create a main function that performs all the cleaning and formatting.

Write these functions in separate .py file(s). By putting these steps into functions, we can make the code more modular and easier to maintain.

*Hint: autoreload module is a utility module in Python that allows you to automatically reload modules in the current session when changes are made to the source code. This can be useful in situations where you are actively developing code and want to see the effects of changes you make without having to constantly restart the Python interpreter or Jupyter Notebook kernel.*

In [69]:
from clean import *

df1=pd.read_csv("https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv")
df1

,Customer,ST,GENDER,Education,Customer Lifetime Value,Income,Monthly Premium Auto,Number of Open Complaints,Policy Type,Vehicle Class,Total Claim Amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.59%,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17%,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,764586.18%,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,536307.65%,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323
...,...,...,...,...,...,...,...,...,...,...,...
4003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [70]:
df1=clean_columns(df1)
df1

,customer,st,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.59%,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17%,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,764586.18%,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,536307.65%,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323
...,...,...,...,...,...,...,...,...,...,...,...
4003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [71]:
df1=cleaning_invalid_values(df1)
df1=formatting(df1)
df1=dealing_null_values(df1)
df1

,customer,st,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount
0,RB50392,Washington,Unknown,Master,NaN,0,1000,0,Personal Auto,Four-Door Car,2
1,QZ44356,Arizona,F,Bachelor,697953.0,0,94,0,Personal Auto,Four-Door Car,1131
2,AI49188,Nevada,F,Bachelor,1288743.0,48767,108,0,Personal Auto,Two-Door Car,566
3,WW63253,California,M,Bachelor,764586.0,0,106,0,Corporate Auto,SUV,529
4,GA49547,Washington,M,High School or Below,536307.0,36357,68,0,Personal Auto,Four-Door Car,17
...,...,...,...,...,...,...,...,...,...,...,...
1066,TM65736,Oregon,M,Master,305955.0,38644,78,1,Personal Auto,Four-Door Car,361
1067,VJ51327,California,F,High School or Below,2031499.0,63209,102,2,Personal Auto,SUV,207
1068,GS98873,Arizona,F,Bachelor,323912.0,16061,88,0,Personal Auto,Four-Door Car,633
1069,CW49887,California,F,Master,462680.0,79487,114,0,Special Auto,SUV,547
1070,MY31220,California,F,College,899704.0,54230,112,0,Personal Auto,Two-Door Car,537

# Bonus: Challenge 3: Analyzing Clean and Formated Data

You have been tasked with analyzing the data to identify potential areas for improving customer retention and profitability. Your goal is to identify customers with a high policy claim amount and a low customer lifetime value.

In the Pandas Lab, we only looked at high policy claim amounts because we couldn't look into low customer lifetime values. If we had tried to work with that column, we wouldn't have been able to because customer lifetime value wasn't clean and in its proper format. So after cleaning and formatting the data, let's get some more interesting insights!

Instructions:

- Review the statistics again for total claim amount and customer lifetime value to gain an understanding of the data.
- To identify potential areas for improving customer retention and profitability, we want to focus on customers with a high policy claim amount and a low customer lifetime value. Consider customers with a high policy claim amount to be those in the top 25% of the total claim amount, and clients with a low customer lifetime value to be those in the bottom 25% of the customer lifetime value. Create a pandas DataFrame object that contains information about customers with a policy claim amount greater than the 75th percentile and a customer lifetime value in the bottom 25th percentile.
- Use DataFrame methods to calculate summary statistics about the high policy claim amount and low customer lifetime value data. To do so, select both columns of the dataframe simultaneously and pass it to the `.describe()` method. This will give you descriptive statistics, such as mean, median, standard deviation, minimum and maximum values for both columns at the same time, allowing you to compare and analyze their characteristics.

In [81]:
# Your code here
condition1 = df1["total_claim_amount"].describe().iloc[6]

In [82]:
condition2 = df1.loc[df1["customer_lifetime_value"].notna(),"customer_lifetime_value"].describe().iloc[4]

In [89]:
df1[(df1["total_claim_amount"]>condition1) & (df1["customer_lifetime_value"] < condition2) & df1["customer_lifetime_value"].notna() ]

,customer,st,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount
17,OE15005,California,Unknown,College,394524.0,28855,101,0,Personal Auto,SUV,647
23,TZ98966,Nevada,Unknown,Bachelor,245019.0,0,73,3,Corporate Auto,Four-Door Car,554
26,US89481,California,Unknown,Bachelor,394637.0,0,111,0,Personal Auto,Four-Door Car,799
38,CM61827,Oregon,Unknown,Bachelor,309003.0,0,90,0,Personal Auto,Two-Door Car,648
42,IL19217,California,Unknown,Bachelor,393900.0,60021,99,0,Personal Auto,Four-Door Car,882
62,FG63582,Oregon,Unknown,Bachelor,333976.0,0,94,0,Personal Auto,Two-Door Car,863
135,MS41162,Arizona,Unknown,High School or Below,402296.0,0,117,0,Personal Auto,SUV,975
140,DS81757,Oregon,M,College,247012.0,0,74,0,Personal Auto,Two-Door Car,721
158,KA61892,Arizona,M,College,387364.0,28142,105,0,Personal Auto,Luxury,701
160,ND87334,California,M,High School or Below,228759.0,0,63,0,Corporate Auto,Two-Door Car,679
170,TS19868,California,M,College,241313.0,27501,63,0,Personal Auto,Four-Door Car,542
184,AB13432,California,M,Bachelor,373583.0,0,110,0,Personal Auto,SUV,792
204,FL34139,California,M,High School or Below,368811.0,0,63,3,Personal Auto,Four-Door Car,669
250,IA63417,Arizona,F,High School or Below,400151.0,19782,108,0,Personal Auto,Two-Door Car,773
269,VZ51506,Arizona,F,High School or Below,359531.0,0,103,0,Corporate Auto,Luxury,741
279,OH60605,Oregon,F,High School or Below,365253.0,39679,92,0,Personal Auto,Two-Door Car,641
304,RR77985,Oregon,F,Bachelor,288774.0,0,80,0,Personal Auto,Four-Door Car,676
388,JF36291,California,M,College,387364.0,28142,105,0,Personal Auto,Luxury,701
415,ZF84449,Oregon,F,College,372672.0,0,112,1,Special Auto,Luxury,806
448,NL93182,Nevada,M,Bachelor,254945.0,0,78,0,Corporate Auto,Four-Door Car,845
450,WE68644,Oregon,F,Bachelor,380392.0,20325,100,0,Personal Auto,Luxury,668
467,AU96286,Oregon,F,Bachelor,316765.0,0,92,0,Corporate Auto,Four-Door Car,662
486,FY51713,Arizona,F,Bachelor,357076.0,56168,88,0,Personal Auto,Four-Door Car,614
500,XN11823,Nevada,F,Bachelor,376446.0,92600,94,0,Corporate Auto,Two-Door Car,842
502,PX17116,Nevada,M,College,362345.0,0,111,2,Corporate Auto,SUV,1171
565,XS12556,California,F,College,368309.0,0,101,0,Corporate Auto,Luxury,564
590,UK41984,Arizona,F,Doctor,383960.0,0,112,2,Personal Auto,SUV,537
593,ZK21724,Oregon,F,High School or Below,401654.0,0,111,0,Personal Auto,SUV,799
638,DM95829,California,M,College,252395.0,16244,68,0,Personal Auto,Two-Door Car,623
645,JA41698,Nevada,M,Bachelor,309953.0,0,102,5,Corporate Auto,SUV,862
669,ED50963,California,F,High School or Below,268886.0,32808,68,1,Personal Auto,Four-Door Car,541
709,NZ15548,Oregon,M,Bachelor,402381.0,41833,103,0,Personal Auto,Four-Door Car,643
788,TE13577,Oregon,F,College,231973.0,0,64,0,Personal Auto,Four-Door Car,632
853,TV25678,Washington,M,College,354090.0,0,101,0,Personal Auto,SUV,727
891,KJ87930,California,F,Bachelor,388650.0,0,112,0,Corporate Auto,SUV,1185
908,XM72420,Arizona,F,High School or Below,391936.0,66676,97,0,Personal Auto,Four-Door Car,558
949,TD10493,Oregon,F,High School or Below,289873.0,0,96,4,Personal Auto,Four-Door Car,691
1019,OT52034,California,M,Bachelor,386477.0,24204,99,1,Personal Auto,Four-Door Car,707
1022,UI73201,California,M,College,366737.0,62375,92,0,Personal Auto,Two-Door Car,618
1068,GS98873,Arizona,F,Bachelor,323912.0,16061,88,0,Personal Auto,Four-Door Car,633

In [86]:
df2=df1[df1["customer_lifetime_value"].notna()]

In [88]:
df2[(df2["total_claim_amount"]>condition1) & (df2["customer_lifetime_value"] < condition2)]

,customer,st,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount
17,OE15005,California,Unknown,College,394524.0,28855,101,0,Personal Auto,SUV,647
23,TZ98966,Nevada,Unknown,Bachelor,245019.0,0,73,3,Corporate Auto,Four-Door Car,554
26,US89481,California,Unknown,Bachelor,394637.0,0,111,0,Personal Auto,Four-Door Car,799
38,CM61827,Oregon,Unknown,Bachelor,309003.0,0,90,0,Personal Auto,Two-Door Car,648
42,IL19217,California,Unknown,Bachelor,393900.0,60021,99,0,Personal Auto,Four-Door Car,882
62,FG63582,Oregon,Unknown,Bachelor,333976.0,0,94,0,Personal Auto,Two-Door Car,863
135,MS41162,Arizona,Unknown,High School or Below,402296.0,0,117,0,Personal Auto,SUV,975
140,DS81757,Oregon,M,College,247012.0,0,74,0,Personal Auto,Two-Door Car,721
158,KA61892,Arizona,M,College,387364.0,28142,105,0,Personal Auto,Luxury,701
160,ND87334,California,M,High School or Below,228759.0,0,63,0,Corporate Auto,Two-Door Car,679
170,TS19868,California,M,College,241313.0,27501,63,0,Personal Auto,Four-Door Car,542
184,AB13432,California,M,Bachelor,373583.0,0,110,0,Personal Auto,SUV,792
204,FL34139,California,M,High School or Below,368811.0,0,63,3,Personal Auto,Four-Door Car,669
250,IA63417,Arizona,F,High School or Below,400151.0,19782,108,0,Personal Auto,Two-Door Car,773
269,VZ51506,Arizona,F,High School or Below,359531.0,0,103,0,Corporate Auto,Luxury,741
279,OH60605,Oregon,F,High School or Below,365253.0,39679,92,0,Personal Auto,Two-Door Car,641
304,RR77985,Oregon,F,Bachelor,288774.0,0,80,0,Personal Auto,Four-Door Car,676
388,JF36291,California,M,College,387364.0,28142,105,0,Personal Auto,Luxury,701
415,ZF84449,Oregon,F,College,372672.0,0,112,1,Special Auto,Luxury,806
448,NL93182,Nevada,M,Bachelor,254945.0,0,78,0,Corporate Auto,Four-Door Car,845
450,WE68644,Oregon,F,Bachelor,380392.0,20325,100,0,Personal Auto,Luxury,668
467,AU96286,Oregon,F,Bachelor,316765.0,0,92,0,Corporate Auto,Four-Door Car,662
486,FY51713,Arizona,F,Bachelor,357076.0,56168,88,0,Personal Auto,Four-Door Car,614
500,XN11823,Nevada,F,Bachelor,376446.0,92600,94,0,Corporate Auto,Two-Door Car,842
502,PX17116,Nevada,M,College,362345.0,0,111,2,Corporate Auto,SUV,1171
565,XS12556,California,F,College,368309.0,0,101,0,Corporate Auto,Luxury,564
590,UK41984,Arizona,F,Doctor,383960.0,0,112,2,Personal Auto,SUV,537
593,ZK21724,Oregon,F,High School or Below,401654.0,0,111,0,Personal Auto,SUV,799
638,DM95829,California,M,College,252395.0,16244,68,0,Personal Auto,Two-Door Car,623
645,JA41698,Nevada,M,Bachelor,309953.0,0,102,5,Corporate Auto,SUV,862
669,ED50963,California,F,High School or Below,268886.0,32808,68,1,Personal Auto,Four-Door Car,541
709,NZ15548,Oregon,M,Bachelor,402381.0,41833,103,0,Personal Auto,Four-Door Car,643
788,TE13577,Oregon,F,College,231973.0,0,64,0,Personal Auto,Four-Door Car,632
853,TV25678,Washington,M,College,354090.0,0,101,0,Personal Auto,SUV,727
891,KJ87930,California,F,Bachelor,388650.0,0,112,0,Corporate Auto,SUV,1185
908,XM72420,Arizona,F,High School or Below,391936.0,66676,97,0,Personal Auto,Four-Door Car,558
949,TD10493,Oregon,F,High School or Below,289873.0,0,96,4,Personal Auto,Four-Door Car,691
1019,OT52034,California,M,Bachelor,386477.0,24204,99,1,Personal Auto,Four-Door Car,707
1022,UI73201,California,M,College,366737.0,62375,92,0,Personal Auto,Two-Door Car,618
1068,GS98873,Arizona,F,Bachelor,323912.0,16061,88,0,Personal Auto,Four-Door Car,633